### PR TITLE
Added password key connected users tab

### PR DESCRIPTION
**Pull request by vipinlalcm**
Added 3 tabs under password key which will list information, attribute and users connected to it. It will list to admin users and non-admin users it will not show the users connected tab itself.

### CODE REVIEW

**Review by stemid — CHANGES_REQUESTED** [review]
lines 40-44 in password.py could probably be replaced by ``pm.render_var['is_admin'] = request.session['administrator']`` right?

The loop on line 46 probably needs some corrections. You're filtering 'user manager local' in listChildren, which means you won't get any ldap or AD user managers in your result. 

You can get the currently active user manager from ViewTree, in your case try doing ``view_tree = pk.getParent('view tree')`` and then ``um = view_tree.user_manager``.

**Comment by stemid** [comment]
Actually you already have the ViewTree instance, ``view.parent`` is ViewTree. So use that and get the user_manager attribute which is the currently active user manager. As far as I know there can be only one active user manager.

**Comment by vipinlalcm** [comment]
Yes, pm.render_var['is_admin'] = request.session['administrator'] . Here I am checking the admin user session and non-admin user.

Also I have made the new changes on the password.py code as well.

**Review by stemid — CHANGES_REQUESTED** [review]
I've tested the code and I would prefer if you put the for loop inside a conditional block so it only runs for admin users. There is a significant slow down with the new code when viewing a password key. 

Also lines 40-44 are still redundant, helpers.PageManager already includes the administrator value. See [here](https://github.com/sii/siptrackweb/blob/master/siptrackweb/views/helpers.py#L86).

So if you need to check whether or not the user is admin in the template, you can use the administrator value which is global.

**Review by stemid — APPROVED** [review]
Now it's looking good.

**Comment by vipinlalcm** [comment]
Thanks for applying the corrections.

**Pull request merged**
